M48
; DRILL file {KiCad (6.0.5)} date Sat Jun  4 22:27:33 2022
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2022-06-04T22:27:33+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.5)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.1004
%
G90
G05
T1
X5.3431Y-3.1242
X5.3431Y-4.0376
X6.1581Y-3.1242
X6.1581Y-4.0376
T0
M30
